[tools]
go = "1.23.10"
"go:golang.org/x/tools/gopls" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:@vue/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:oxlint" = "latest"
"npm:pyright" = "latest"
"npm:typescript-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:yaml-language-server" = "latest"
"pipx:basedpyright" = "latest"
"pipx:ruff" = "latest"
ripgrep = "latest"
jq = "latest"
yq = "latest"
github-cli = "latest"
fd = "latest"
ast-grep = "latest"
